server:
  port: 8080
spring:
  application:
    name: service-auth
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pass-genius
  logging:
    level:
      org.springframework: DEBUG

